name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch GitHub Stats
        id: stats
        run: |
          # Fetch total commit count from all repositories
          TOTAL_COMMITS=$(curl -s -H "Accept: application/vnd.github+json" "https://api.github.com/search/commits?q=author:Hydrovolter" | jq '.total_count')
          
          # Fetch all repositories and sum up stargazers_count
          TOTAL_STARS=$(curl -s "https://api.github.com/users/Hydrovolter/repos?per_page=100" | jq '[.[] | .stargazers_count] | add')
          
          echo "TOTAL_COMMITS=$TOTAL_COMMITS" >> $GITHUB_ENV
          echo "TOTAL_STARS=$TOTAL_STARS" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/Commits: [0-9]\+/Commits: $TOTAL_COMMITS/" README.md
          sed -i "s/Stars: [0-9]\+/Stars: $TOTAL_STARS/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update GitHub stats in README" || echo "No changes to commit"
          git push
