name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch GitHub Stats
        id: stats
        run: |
          COMMITS=$(curl -s "https://api.github.com/users/Hydrovolter" | jq '.public_repos')
          STARS=$(curl -s "https://api.github.com/users/Hydrovolter" | jq '[.repos_url] | map(select(.stargazers_count)) | add')
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          echo "STARS=$STARS" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/Commits: [0-9]\+/Commits: $COMMITS/" README.md
          sed -i "s/Stars: [0-9]\+/Stars: $STARS/" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update GitHub stats in README" || echo "No changes to commit"
          git push
